export const packagesList = {
  // month
  packagesPerMonthEn: [
    {
      __id: "1",
      packageName: "Silver",
      originalPrice: "500",
      offerPrice: "399",
      type: "SAR/month",
      features: [
        "Property and Asset Management",
        "Tenant Login Portal",
        "Smart Dashboard",
        "Contract and Payment Management",
        "Revenue and Expense Management",
        "Operational and Financial Task Management",
        "Document Upload",
        "Customer and Operational Reports",
        "Tenant SMS Notifications",
      ],
    },
    {
      __id: "2",
      packageName: "Golden",
      originalPrice: "800",
      offerPrice: "699",
      type: "SAR/month",
      features: [
        "Property and Asset Management",
        "Tenant Login Portal",
        "Advanced Smart Dashboard",
        "Automated Contract and Payment Management",
        "Comprehensive Revenue and Expense Analytics",
        "Task Automation and Workflow Management",
        "Secure Document Upload and Storage",
        "Enhanced Customer and Operational Reports",
        "Tenant Email and SMS Notifications",
        "Priority Customer Support",
      ],
    },
    {
      __id: "3",
      packageName: "Platinum",
      originalPrice: "1200",
      offerPrice: "999",
      type: "SAR/month",
      features: [
        "All-in-One Property Management",
        "Custom Tenant Login Portal",
        "Real-Time Smart Dashboard",
        "Automated Contract Renewal and Payments",
        "Detailed Revenue, Expense, and Tax Reports",
        "Full Operational Task Automation",
        "Unlimited Document Storage",
        "Comprehensive Analytics and Insights",
        "Multi-Channel Tenant Notifications",
        "Dedicated Account Manager",
      ],
    },
  ],
  packagePerMonthAr: [
    {
      __id: "ar_1",
      packageName: "الفضة",
      originalPrice: "500",
      offerPrice: "399",
      type: "ريال/شهر",
      features: [
        "إدارة العقارات والأصول",
        "بوابة دخول للمؤجرةين",
        "لوحة تحكم ذكية",
        "إدارة العقود والمدفوعات",
        "إدارة الإيرادات والمصاريف",
        "إدارة المهام التشغيلية والمالية",
        "تحميل الوثائق",
        "تقارير العملاء والعمليات",
        "إشعارات المؤجرة عبر الرسائل القصيرة",
      ],
    },
    {
      __id: "ar_2",
      packageName: "الذهب",
      originalPrice: "800",
      offerPrice: "699",
      type: "ريال/شهر",
      features: [
        "إدارة العقارات والأصول",
        "بوابة دخول للمؤجرةين",
        "لوحة تحكم ذكية متقدمة",
        "إدارة العقود والمدفوعات الآلية",
        "تحليلات شاملة للدخل والمصاريف",
        "أتمتة المهام وسير العمل",
        "تحميل وتخزين آمن للوثائق",
        "تقارير محسّنة للعملاء والعمليات",
        "إشعارات المستأجر عبر البريد الإلكتروني والرسائل القصيرة",
        "دعم عملاء أولوية",
      ],
    },
    {
      __id: "ar_3",
      packageName: "البلاتين",
      originalPrice: "1200",
      offerPrice: "999",
      type: "ريال/شهر",
      features: [
        "إدارة عقارات شاملة",
        "بوابة مخصصة للمستأجرين",
        "لوحة تحكم ذكية في الوقت الحقيقي",
        "تجديد العقود والدفع الآلي",
        "تقارير تفصيلية للدخل والمصاريف والضرائب",
        "أتمتة كاملة للمهام التشغيلية",
        "تخزين غير محدود للوثائق",
        "تحليلات شاملة ورؤى متقدمة",
        "إشعارات متعددة القنوات (البريد الإلكتروني، الرسائل القصيرة، واتساب)",
        "مدير حساب مخصص",
      ],
    },
  ],

  // 3 months
  packagePerThreeMonthsEn: [
    {
      __id: "4",
      packageName: "Silver",
      originalPrice: "1500",
      offerPrice: "1299",
      type: "SAR/3 months",
      features: [
        "Property and Asset Management",
        "Tenant Login Portal",
        "Smart Dashboard",
        "Quarterly Payment Tracking",
        "Basic Revenue and Expense Reports",
        "Operational Task Management",
        "Document Upload",
        "Customer Reports",
        "Tenant SMS Notifications",
      ],
    },
    {
      __id: "5",
      packageName: "Golden",
      originalPrice: "2400",
      offerPrice: "1999",
      type: "SAR/3 months",
      features: [
        "Property Management and Asset Tracking",
        "Tenant Portal Access",
        "Advanced Dashboard with Analytics",
        "Quarterly Contract and Payment Management",
        "Revenue and Expense Optimization",
        "Automated Financial Reports",
        "Bulk Document Uploads",
        "Customer and Operational Insights",
        "Scheduled Tenant Notifications",
      ],
    },
    {
      __id: "6",
      packageName: "Platinum",
      originalPrice: "3600",
      offerPrice: "2999",
      type: "SAR/3 months",
      features: [
        "Complete Property Management Suite",
        "Personalized Tenant Login Portal",
        "Live Smart Dashboard",
        "Automated Payment Processing",
        "Quarterly Financial Reviews",
        "Full Workflow Automation",
        "Unlimited Secure Document Storage",
        "Advanced Customer Analytics",
        "Multi-Channel Notifications",
        "24/7 Priority Support",
      ],
    },
  ],
  packagePerThreeMonthsAr: [
    {
      __id: "ar_4",
      packageName: "الفضة",
      originalPrice: "5000",
      offerPrice: "4000",
      type: "ريال/3 أشهر",
      features: [
        "إدارة العقارات والأصول",
        "بوابة دخول للمستأجرين",
        "لوحة تحكم ذكية",
        "تتبع المدفوعات ربع سنوي",
        "تقارير أساسية للدخل والمصاريف",
        "إدارة المهام التشغيلية",
        "تحميل الوثائق",
        "تقارير العملاء",
        "إشعارات المستأجر عبر الرسائل القصيرة",
      ],
    },
    {
      __id: "ar_5",
      packageName: "الذهب",
      originalPrice: "2400",
      offerPrice: "2000",
      type: "ريال/3 أشهر",
      features: [
        "إدارة العقارات وتتبع الأصول",
        "وصول إلى بوابة المستأجرين",
        "لوحة تحكم متقدمة مع تحليلات",
        "إدارة العقود والمدفوعات ربع سنوية",
        "تحسين الإيرادات والمصاريف",
        "تقارير مالية آلية",
        "تحميل وثائق بالجملة",
        "رؤى العملاء والعمليات",
        "إشعارات مجدولة للمستأجرين",
      ],
    },
    {
      __id: "ar_6",
      packageName: "البلاتين",
      originalPrice: "3600",
      offerPrice: "3000",
      type: "ريال/3 أشهر",
      features: [
        "جناح إدارة العقارات الشامل",
        "بوابة دخول مخصصة للمستأجرين",
        "لوحة تحكم ذكية مباشرة",
        "معالجة مدفوعات آلية",
        "مراجعات مالية ربع سنوية",
        "أتمتة كاملة لسير العمل",
        "تخزين آمن غير محدود للوثائق",
        "تحليلات متقدمة للعملاء",
        "إشعارات متعددة القنوات",
        "دعم على مدار الساعة",
      ],
    },
  ],

  // year
  packagePerYearEn: [
    {
      __id: "7",
      packageName: "Silver",
      originalPrice: "6000",
      offerPrice: "4999",
      type: "SAR/year",
      features: [
        "Property and Asset Management",
        "Tenant Portal Access",
        "Basic Smart Dashboard",
        "Annual Contract and Payment Tracking",
        "Revenue and Expense Management",
        "Basic Operational Reports",
        "Document Upload",
        "Scheduled Customer Reports",
        "Tenant SMS Notifications",
      ],
    },
    {
      __id: "8",
      packageName: "Golden",
      originalPrice: "9600",
      offerPrice: "7999",
      type: "SAR/year",
      features: [
        "Property and Asset Management",
        "Tenant Portal with Customization",
        "Smart Dashboard with Annual Insights",
        "Automated Contract Management",
        "Full Revenue, Expense, and Tax Reports",
        "Annual Financial Reviews",
        "Document Upload and Archive",
        "Customer and Market Reports",
        "Automated Tenant Notifications",
        "Priority Support",
      ],
    },
    {
      __id: "9",
      packageName: "Platinum",
      originalPrice: "14400",
      offerPrice: "11999",
      type: "SAR/year",
      features: [
        "Comprehensive Property Management Suite",
        "Advanced Tenant Login Portal",
        "Real-Time Smart Dashboard with AI Insights",
        "Full Contract and Payment Automation",
        "Complete Financial and Tax Analytics",
        "Annual Strategy Reports",
        "Unlimited Document Archive",
        "In-Depth Market Analytics",
        "Multi-Channel Tenant Communication",
        "Dedicated Account Manager and VIP Support",
      ],
    },
  ],
  packagePerYearAr: [
    {
      __id: "ar_7",
      packageName: "الفضة",
      originalPrice: "6000",
      offerPrice: "4999",
      type: "ريال/سنة",
      features: [
        "إدارة العقارات والأصول",
        "وصول إلى بوابة المستأجرين",
        "لوحة تحكم ذكية أساسية",
        "تتبع العقود والمدفوعات السنوية",
        "إدارة الإيرادات والمصاريف",
        "تقارير تشغيلية أساسية",
        "تحميل الوثائق",
        "تقارير مجدولة للعملاء",
        "إشعارات المستأجر عبر الرسائل القصيرة",
      ],
    },
    {
      __id: "ar_8",
      packageName: "الذهب",
      originalPrice: "9600",
      offerPrice: "7999",
      type: "ريال/سنة",
      features: [
        "إدارة العقارات والأصول",
        "بوابة مستأجرين مخصصة",
        "لوحة تحكم ذكية برؤى سنوية",
        "إدارة العقود آليًا",
        "تقارير شاملة للدخل والمصاريف والضرائب",
        "مراجعات مالية سنوية",
        "تحميل وأرشفة الوثائق",
        "تقارير العملاء والسوق",
        "إشعارات آلية للمستأجرين",
        "دعم أولوية",
      ],
    },
    {
      __id: "ar_9",
      packageName: "البلاتين",
      originalPrice: "14400",
      offerPrice: "11999",
      type: "ريال/سنة",
      features: [
        "جناح إدارة العقارات الشامل",
        "بوابة دخول متقدمة للمستأجرين",
        "لوحة تحكم ذكية فورية بذكاء اصطناعي",
        "أتمتة العقود والمدفوعات بالكامل",
        "تحليلات مالية وضريبية شاملة",
        "تقارير استراتيجية سنوية",
        "أرشيف غير محدود للوثائق",
        "تحليلات متعمقة للسوق",
        "اتصالات متعددة القنوات مع المستأجرين",
        "مدير حساب مخصص ودعم VIP",
      ],
    },
  ],
};

export const realEstates = [
  { label: "Riyadh Building", value: "Riyadh Building" },
  { label: "Asmara Compund", value: "Asmara Compund" },
];

export const properties = [
  {
    _id: 1,
    name: "Al-Masif Villa",
    image: "b1",
    state: "Vacant",
    compound: "Masif Compound",
    address: "Al-Masif St, Riyadh",
    region: "Riyadh Province",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 2,
    name: "Jeddah Tower",
    image: "b2",
    state: "Rented",
    compound: "Jeddah Towers",
    address: "Beachfront,Jeddah",
    region: "Riyadh Province",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 3,
    name: "Beach House",
    image: "b3",
    state: "Reserved",
    compound: "Riyadh Villas",
    address: "Beachfront,Jeddah",
    region: "Makkah Province",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 4,
    name: "Makkah Luxury",
    image: "b4",
    state: "Rented",
    compound: "Res_idences",
    address: "King Abdulaziz Road, Makkah",
    region: "Makkah Province",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 5,
    name: "Al-Khobar Duplex",
    image: "b1",
    state: "Vacant",
    compound: "Al-Khobar Heights",
    address: "Al-Khobar, Eastern Province",
    region: "Eastern Province",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];

export const arProperties = [
  {
    _id: "ar_1",
    name: "فيلا المصيف",
    image: "b1",
    state: "شاغرة",
    compound: "مجمع المصيف",
    address: "شارع المصيف، الرياض",
    region: "منطقة الرياض",
    description: "لوريم إيبسوم دولور سيت أميت كونسكتتور أديبيسيسينغ إليت.",
  },
  {
    _id: "ar_2",
    name: "برج جدة",
    image: "b2",
    state: "مؤجرة",
    compound: "أبراج جدة",
    address: "الواجهة البحرية، جدة",
    region: "منطقة الرياض",
    description: "لوريم إيبسوم دولور سيت أميت كونسكتتور أديبيسيسينغ إليت.",
  },
  {
    _id: "ar_3",
    name: "البيت الشاطئي",
    image: "b3",
    state: "محجوزة",
    compound: "فلل الرياض",
    address: "الواجهة البحرية، جدة",
    region: "منطقة مكة المكرمة",
    description: "لوريم إيبسوم دولور سيت أميت كونسكتتور أديبيسيسينغ إليت.",
  },
  {
    _id: "ar_4",
    name: "الرفاهية في مكة",
    image: "b4",
    state: "مؤجرة",
    compound: "ريزيدنس",
    address: "طريق الملك عبد العزيز، مكة",
    region: "منطقة مكة المكرمة",
    description: "لوريم إيبسوم دولور سيت أميت كونسكتتور أديبيسيسينغ إليت.",
  },
  {
    _id: "ar_5",
    name: "دوبلكس الخبر",
    image: "b1",
    state: "شاغرة",
    compound: "هايتس الخبر",
    address: "الخبر، المنطقة الشرقية",
    region: "المنطقة الشرقية",
    description: "لوريم إيبسوم دولور سيت أميت كونسكتتور أديبيسيسينغ إليت.",
  },
];

export const SaudiRegion = [
  { label: "Riyadh", value: "Riyadh" },
  { label: "Makkah", value: "Makkah" },
  { label: "Al-Madinah", value: "Madinah" },
  { label: "Al-Qassim", value: "Al-Qassim" },
  { label: "Eastern", value: "Eastern" },
];

export const citiesByRegion = {
  Riyadh: [
    { label: "Al Malaz", value: "Al Malaz" },
    { label: "Al Olaya", value: "Al Olaya" },
  ],
  Makkah: [
    { label: "Jeddah", value: "Jeddah" },
    { label: "Taif", value: "Taif" },
  ],
  Madinah: [
    { label: "Yanbu", value: "Yanbu" },
    { label: "Al-Ula", value: "Al-Ula" },
  ],
  "Al-Qassim": [
    { label: "Buraydah", value: "Buraydah" },
    { label: "Unaizah", value: "Unaizah" },
  ],
  Eastern: [
    { label: "Dammam", value: "Dammam" },
    { label: "Al Khobar", value: "Al Khobar" },
  ],
};

export const districtsByCity = {
  "Al Malaz": [{ label: "District 1", value: "District 1" }],
  "Al Olaya": [{ label: "District 2", value: "District 2" }],
  Jeddah: [{ label: "District 3", value: "District 3" }],
  Taif: [{ label: "District 4", value: "District 4" }],
};



export const tagOptions=[
  {label:"block1",value:"block1"},
  {label:"block2",value:"block2"},
  {label:"block3",value:"block3"},
]

export const agents=[
  {label:"Ahmed",value:"Ahmed"},
  {label:"Salim",value:"Salim"},
  {label:"Said",value:"Said"},
]